# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artbud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='price',
            field=models.CharField(max_length=128),
        ),
    ]
