# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artbud', '0005_auto_20170224_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
