# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artbud', '0006_userprofile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='artwork',
            field=models.ImageField(blank=True, upload_to='artwork_images'),
        ),
    ]
