# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artbud', '0008_artwork_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='category',
        ),
    ]
