# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artbud', '0009_remove_upload_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='category',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='user',
        ),
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='comment',
            field=models.CharField(default=' ', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Artwork',
        ),
    ]
